TWEAK_NAME = Athena
Athena_FILES = Athena.m $(wildcard Views/*.m)
Athena_CFLAGS = -fobjc-arc -DTHEOS_LEAN_AND_MEAN
Athena_FRAMEWORKS = UIKit CoreText

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
