BUNDLE_NAME = AthenaPreferences
AthenaPreferences_FILES = $(wildcard Controllers/*.m Cells/*.m)
AthenaPreferences_FRAMEWORKS = UIKit
AthenaPreferences_PRIVATE_FRAMEWORKS = Preferences
AthenaPreferences_INSTALL_PATH = /Library/PreferenceBundles
AthenaPreferences_CFLAGS = -fobjc-arc -DTHEOS_LEAN_AND_MEAN

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
